package com.trademesh.backend.engine;

import com.trademesh.backend.entity.OrderStatus;

import java.math.BigDecimal;
import java.util.List;

/**
 * Outcome of submitting one order to an {@link OrderBook}.
 *
 * @param trades the trades generated by this call
 * @param affectedRestingOrders every resting order whose state changed
 *     (partially or fully filled) during this match, so a persistence layer
 *     knows which DB rows besides the incoming order need updating
 * @param finalStatus the incoming order's own post-match status
 * @param remainingQuantity the incoming order's own post-match remaining quantity
 */
public record MatchResult(List<EngineTrade> trades, List<EngineOrder> affectedRestingOrders,
                           OrderStatus finalStatus, BigDecimal remainingQuantity) {

    public MatchResult {
        trades = List.copyOf(trades);
        affectedRestingOrders = List.copyOf(affectedRestingOrders);
    }
}
