-- Trademesh uses a single Postgres database (trademesh_db) with one schema
-- per stateful service, rather than separate databases.

CREATE SCHEMA IF NOT EXISTS auth;
CREATE SCHEMA IF NOT EXISTS orders;
CREATE SCHEMA IF NOT EXISTS portfolio;

GRANT ALL PRIVILEGES ON SCHEMA auth TO trademesh;
GRANT ALL PRIVILEGES ON SCHEMA orders TO trademesh;
GRANT ALL PRIVILEGES ON SCHEMA portfolio TO trademesh;

ALTER DEFAULT PRIVILEGES IN SCHEMA auth GRANT ALL ON TABLES TO trademesh;
ALTER DEFAULT PRIVILEGES IN SCHEMA orders GRANT ALL ON TABLES TO trademesh;
ALTER DEFAULT PRIVILEGES IN SCHEMA portfolio GRANT ALL ON TABLES TO trademesh;

ALTER DEFAULT PRIVILEGES IN SCHEMA auth GRANT ALL ON SEQUENCES TO trademesh;
ALTER DEFAULT PRIVILEGES IN SCHEMA orders GRANT ALL ON SEQUENCES TO trademesh;
ALTER DEFAULT PRIVILEGES IN SCHEMA portfolio GRANT ALL ON SEQUENCES TO trademesh;
