spring:
  application:
    name: trademesh-backend

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  datasource:
    url: jdbc:postgresql://localhost:5432/trademesh
    username: trademesh
    password: trademesh
    driver-class-name: org.postgresql.Driver

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

---
spring:
  config:
    activate:
      on-profile: docker

  datasource:
    url: jdbc:postgresql://postgres:5432/trademesh
    username: trademesh
    password: trademesh
