server:
  port: 8084

spring:
  application:
    name: portfolio-service
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:trademesh_db}
    username: ${DB_USER:trademesh}
    password: ${DB_PASSWORD:trademesh}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: portfolio
        format_sql: true
    open-in-view: false

grpc:
  server:
    port: 9092

logging:
  level:
    com.trademesh: INFO
